### PR TITLE
fix: change reqwest to use rustls instead of OpenSSL to avoid build

### PR DESCRIPTION
**Pull request by Weasy666**
and run problems on some platforms like Alpine MUSL

### CODE REVIEW

**Comment by fMeow** [comment]
I don't know if it is a good idea to force all users to use rustls instead of openssl for reqwest. 

I think you can turn on the `rustls` feature for reqest in the `Cargo.toml` in your own application. Since cargo only compile a crate once for a major version, this should work as long as you use the same version of reqwest in arangors and your own app.

**Comment by Weasy666** [comment]
Yeah ok, that makes sense. But would you maybe be open to new feature flags?
```toml
reqwest_async_rustls = [ "reqwest/rustls-tls"]
reqwest_blocking_rustls = [ "reqwest/blocking", "reqwest/rustls-tls", "blocking" ] <-- not sure if it works like this
```

**Comment by fMeow** [comment]
That's ok I think. But I doubt its necessity.

> In addition, I think there is a way to use `rustls` instead of `openssl` without modifying arangors code. You can turn on the `rustls` feature for reqwest in the `Cargo.toml` of your own application. Since cargo only compile a crate once for a major version, this should work as long as you use the same version of reqwest in arangors and your own app.

I will test if my suggetion works as I think. If not, then a new feature flag is necessary. Otherwise an update on readme should do the trick. I am reluctant to add new feature gate for dependency since another user might want another feature for reqwest, and this is endless.

**Comment by fMeow** [comment]
Due to the additive nature of rust feature gate, my proposal does not exclude openssl dependency.

This is really bad. AFAIK, There is three way to solve this. 

1. The first way is to add new feature flags for rustls, and keep native-tls as default.

> Yeah ok, that makes sense. But would you maybe be open to new feature flags?
> 
> ```toml
> reqwest_async_rustls = [ "reqwest/rustls-tls"]
> reqwest_blocking_rustls = [ "reqwest/blocking", "reqwest/rustls-tls", "blocking" ] <-- not sure if it works like this
> ```

2. The second is to remove tls by default, and let the user add tls stack by specifying tls feature gate in their own crate.
```toml
[package]
name = "arangors"

# ....

  [dependencies.reqwest]
  version = "0.10.4"
  default-features = false
  features = [ "gzip", "json" ]
  optional = true
```
```toml
[package]
name = "downstream_package"

[dependencies]
arangors = "0.4"

[dependencies.reqwest]
version = "0.10.9"
default-features = false
features = [ "gzip", "json", "rustls-tls" ]
```
3. And the last is base on solution 2, but add tls feature in arangors instead of let the user specify tls stack on their downstream crate.
```toml
[package]
name = "arangors"

# ....

  [dependencies.reqwest]
  version = "0.10.4"
  default-features = false
  features = [ "gzip", "json" ]
  optional = true

[features]
reqwest_rustls = ["reqwest/rustls"]
reqwest_native_tls = ["reqwest/default-tls"]
```

I think the last two solution are cleaner while the first solution can avoid unanticipated change.

**Comment by Weasy666** [comment]
Have you tested?
```toml
reqwest = { version = "0.10.8", default-features = false, features = ["blocking", "rustls-tls"] }
```
I believe that this tells `reqwest` to not build with any features except the ones specified. Right now, i am not able to test this, but could do it tomorrow.

**Comment by fMeow** [comment]
If another crate require a reqwest with default features, then it actually compiles both openssl and rustls for reqwest. This is the result of the hidden rule that rust feature gate must be additive. 

It does not meet your need, since the motivation of using rustls is to get rid of openssl. And it actually compiles both.

**Comment by fMeow** [comment]
I found a solution, that is to use a vanilla arangors and use a custom [ReqwestClient](https://github.com/fMeow/arangors/blob/master/src/client/reqwest.rs) instead. Though the code can be exactly the same for a client, you can tweak whatever feature you want on reqwest.

I create an [example](https://github.com/fMeow/arangors/tree/master/examples/reqwest_rustls) on how to use reqwest with rustls by implementing custom `ReqwestClient`.

I am still against the idea that to add a new feature gate for rustls, since it can be endless to add features for another set of dependency features.

**Comment by fMeow** [comment]
The new 0.5 added rustls feature gate for reqwest.

**Comment by Weasy666** [comment]
I think this PR can then be closed.

**Pull request closed without merging**
