### PR TITLE
Added examples for DocumentResponse in examples/document.rs

### PR DESCRIPTION
**Pull request by arn-the-long-beard**
Hello !

I started to add few examples for DocumentResponse :)

### CODE REVIEW

**Comment by fMeow** [comment]
Would you like to placd `User` before main function? I think it  a bit confusing when I first came across the `User` type in main function.

I think the `drop_collection` and `create_collection` can be removed. A example is not like a unit test. We can focus on the stuff of concerned only.

Could please add a line by setting options by `Default::default()`? I think most user will use `XXXOption::builder().build()` when they want default options. And we can remind them that `Default::default()` can do the same thing.

**Comment by arn-the-long-beard** [comment]
Thank you :+1: 
Okay :) I will correct  the code !

**Comment by arn-the-long-beard** [comment]
`Default::default()` is hot :+1: 

I removed only one `drop` but I needed the others `create` & `drop` otherwise we have no collection to play with :P

**Comment by arn-the-long-beard** [comment]
I forgot to move the struct User.

**Comment by fMeow** [comment]
That's fine. It's just for readability.

**Pull request merged**
